#define PLUG_NAME "FreqmodGrid"
#define PLUG_MANUFACTURER "FreqMod"
#define PLUG_VERSION 0x010000
#define PLUG_UNIQUE_ID 'FREQ'
#define PLUG_MFR_ID 0x4665724d // "FerM"

#define PLUG_IS_INSTRUMENT 1
#define PLUG_HAS_EDITOR 0
#define PLUG_HAS_MIDI_INPUT 1
#define PLUG_HAS_MIDI_OUTPUT 0
#define PLUG_HAS_VARIABLE_IO 0

#define PLUG_LATENCY 0
#define PLUG_MIN_INPUT_LATENCY 0
#define PLUG_MIN_OUTPUT_LATENCY 0
#define PLUG_MAX_INPUT_LATENCY 0
#define PLUG_MAX_OUTPUT_LATENCY 0

#define PLUG_EDITOR_DEFAULTS 400 300

#define PLUG_VST2_VERSION 2400
